{% set version = "1.5" %}

package:
  name: openap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openap/openap-{{ version }}.tar.gz
  sha256: 5ce3f731993586915f86a0c05380f6de7fc1b5d843cdb15f13b43272397df047

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - pandas
    - pyyaml
    - matplotlib-base

test:
  imports:
    - openap

about:
  home: https://github.com/junzis/openap
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Open Aircraft Performance Model (OpenAP) in Python

extra:
  recipe-maintainers:
    - junzis
    - xoolive
