{% set version = "1.4" %}

package:
  name: openap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openap/openap-{{ version }}.tar.gz
  sha256: 316264e50ea0ae2ce205f823f09bdb566481415e460d03df30a06c5c9faded0f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9
    - numpy >=1.24
    - scipy >=1.7
    - scikit-fuzzy >=0.4
    - pandas >=1.2
    - pyyaml >=5.1
    - matplotlib-base >=3.1

test:
  imports:
    - openap

about:
  home: https://github.com/junzis/openap
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Open Aircraft Performance Model (OpenAP) in Python

extra:
  recipe-maintainers:
    - junzis
    - xoolive
