{% set version = "2.5.0" %}

package:
  name: openap
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/openap/openap-{{ version }}.tar.gz
  sha256: 10a7c6c528b494dd275fcc52c509e71a19e63dd9baa7d455c6c4e64688ea4b1f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - pyyaml
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - openap

about:
  home: https://github.com/junzis/openap
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Open Aircraft Performance Model (OpenAP) in Python

extra:
  recipe-maintainers:
    - junzis
    - xoolive
