{% set version = "2.6.2" %}

package:
  name: openap
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/o/openap/openap-{{ version }}.tar.gz
  sha256: 9c1b370d12f02aeacf2a8112591ac0cb2a733ad7044f4b7bcf251b9bb1121d9d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - pyyaml
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - openap

about:
  home: https://github.com/junzis/openap
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Open Aircraft Performance Model (OpenAP) in Python

extra:
  recipe-maintainers:
    - junzis
    - xoolive
