{% set version = "2.6.0" %}

package:
  name: openap
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/openap/openap-{{ version }}.tar.gz
  sha256: be47e75c5ade7c56b9476fbf45d506a385ed3abfc2185197da6ee7e20ea8ada3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - pyyaml
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - openap

about:
  home: https://github.com/junzis/openap
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Open Aircraft Performance Model (OpenAP) in Python

extra:
  recipe-maintainers:
    - junzis
    - xoolive
