{% set version = "2.4" %}

package:
  name: openap
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/openap/openap-{{ version }}.tar.gz
  sha256: a07b05316dd646bc8e7a1298c47941439f8d40f8bd1e87ce174fcf308406d3aa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - pyyaml
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - openap

about:
  home: https://github.com/junzis/openap
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Open Aircraft Performance Model (OpenAP) in Python

extra:
  recipe-maintainers:
    - junzis
    - xoolive
