{% set version = "2.0" %}

package:
  name: openap
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/openap/openap-{{ version }}.tar.gz
  sha256: fea6801fe0e1cae9c68c81859e82e869050be9a310d499fb94f27a11993f418b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - pyyaml
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - openap

about:
  home: https://github.com/junzis/openap
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Open Aircraft Performance Model (OpenAP) in Python

extra:
  recipe-maintainers:
    - junzis
    - xoolive
